# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, byteable, cereal, cryptohash, cryptoPubkey
, cryptoPubkeyTypes, cryptoRandom, dataLens, json, largeword, mtl
, secp256k1, tasty, tastyHunit, tastyQuickcheck, vector
}:

cabal.mkDerivation (self: {
  pname = "ether";
  version = "0.1.0.0";
  src = ./.;
  buildDepends = [
    byteable cereal cryptohash cryptoPubkey cryptoPubkeyTypes
    cryptoRandom dataLens largeword mtl secp256k1 vector
  ];
  testDepends = [
    byteable cereal cryptohash cryptoPubkey cryptoPubkeyTypes
    cryptoRandom dataLens json largeword mtl secp256k1 tasty tastyHunit
    tastyQuickcheck vector
  ];
  meta = {
    description = "Ethereum in Haskell";
    license = self.stdenv.lib.licenses.gpl3;
    platforms = self.ghc.meta.platforms;
  };
})
